Use the new UserOrganizationMapping and TahoeSiteUUID
appsembler/course-access-groups pull request #98
Opened 2022-01-12 12:04 UTC by shadinaif

**Description:** Describe in a couple of sentences what this PR adds

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation 
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2022-01-17 06:30 UTC, OmarIthawi reviewed
Thanks Shadi. few comments before this PR is confluded.

2022-01-17 06:30 UTC, OmarIthawi commented on .github/workflows/ci.yml
> +          - py3-django2-use_orgs
what's the difference between `py3-django2` and `py3-django2-use_orgs`?

2022-01-18 13:44 UTC, shadinaif commented on course_access_groups/permissions.py
> +from tahoe_sites.models import TahoeSiteUUID
@OmarIthawi I've added it as `@classmethod` to `TahoeSiteUUID` instead of a separate helper. OK?

2022-01-19 09:05 UTC, OmarIthawi reviewed
Thanks @shadinaif! This is amazing. I'm adding few more suggestions to use a new `api.py` module in the new `tahoe-sites` package.

This will have `helpers.py` but can be used externally by other packages such as CAG and Figures.

Here are few examples of such modules:

 - https://github.com/appsembler/edx-organizations/blob/main/organizations/api.py
 - https://github.com/appsembler/edx-platform/blob/main/openedx/core/djangoapps/enrollments/api.py
 - https://github.com/appsembler/edx-platform/blob/main/lms/djangoapps/grades/api.py
 - https://github.com/appsembler/edx-platform/blob/main/lms/djangoapps/gating/api.py

Those API helpers are normal Python helper functions that are more stable than `helpers.py` and the should help to abstract the internal changes of `tahoe-sites` away from other modules that uses those APIs.

Those help to guard against model changes, field name changes, data migration and reduces testing effort in general.

2022-01-19 09:05 UTC, OmarIthawi commented on course_access_groups/views.py
>              ).values('user_id'),
Abstract the `UserOrganizationMapping` away from CAG.

```py
user_ids_queryset = tahoe_sites.apis.get_organizations_user_ids_queryset(organization, include_admins=False)
return self.model.objects.filter(pk__in=user_ids_queryset)
```

2022-01-28 14:42 UTC, shadinaif commented on course_access_groups/permissions.py
>      ).exists()
done

2022-01-28 15:00 UTC, OmarIthawi requested changes
Please fix the `.values(...)`. I think it's mandatory and passing tests can be misleading sometimes. In other words, I don't think tests are working properly for this part.

2022-01-29 09:40 UTC, shadinaif commented on course_access_groups/models.py
> +            pk__in=get_organizations_for_user(user),
the helper does return `values`. But since its confusing; I replaced it with returning objects

2022-01-29 09:41 UTC, shadinaif commented on tests/test_acl_backend.py
> +            is_admin=True,
Done (now), thank you Omar

2022-01-31 08:06 UTC, OmarIthawi approved these changes

2022-01-31 08:07 UTC, OmarIthawi commented
Looks great!! Thanks @shadinaif!

2022-01-31 09:51 UTC, merged